AWSTemplateFormatVersion: '2010-09-09'
Description: CI/CD pipeline for Flask Lambda App

Resources:
  FlaskPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::207567778537:role/FlaskCodePipelineRole
      ArtifactStore:
        Type: S3
        Location: flask-lambda-artifacts-bucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: REWATSING
                Repo: aws_cicd_flask_project
                Branch: master
                OAuthToken: "{{resolve:secretsmanager:GitHubToken:SecretString:token}}"
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: FlaskLambdaBuildProject
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: LambdaDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: Lambda
                Version: 1
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                FunctionName: FlaskLambdaFunction
                ImageUri: 207567778537.dkr.ecr.ap-south-1.amazonaws.com/flask-lambda-repo:latest
              RunOrder: 1
