version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 207567778537.dkr.ecr.ap-south-1.amazonaws.com)
      - REPO_URI=<ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/flask-lambda-ecr
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"FlaskFunction","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
