AWSTemplateFormatVersion: '2010-09-09'
Description: CI/CD pipeline for Flask Lambda

Resources:
  FlaskPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::207567778537:role/CodePipelineRole
      ArtifactStore:
        Type: S3
        Location: flask-lambda-artifacts-1753952051
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: REWATSING
                Repo: aws_cicd_flask_project
                Branch: master
                OAuthToken: "{{resolve:secretsmanager:GitHubToken:SecretString:token}}"
        - Name: Build
          Actions:
            - Name: DockerBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: flask-lambda-codebuild
        - Name: Deploy
          Actions:
            - Name: DeployLambda
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: FlaskLambdaPipelineStack
                Capabilities: CAPABILITY_IAM
                TemplatePath: SourceArtifact::template.yaml
