version = 0.1

[default]
[default.deploy]
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
stack_name = "FlaskLambdaPipelineStack"
s3_bucket = "flask-lambda-artifacts-1753952051"
confirm_changeset = false
resolve_s3 = true
